# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.6
_src_path: gh:hexdoc-dev/hexdoc-mod-template
add_gitignore: true
add_vscode: false
advanced: false
author: hauveli
book_id: hexcasting:thehexbook
capitalize_platforms: false
github_repo: fishcasting
gradle_minecraft_version_key: minecraft_version
gradle_mod_version_key: version
mod_display_name: Fishcasting
modid: fishcasting
multiloader: true
